package com.block.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import java.util.*;

/**
 * Generated by JFinal.
*/
@SuppressWarnings("serial")
public class BaseOrder <M extends BaseOrder<M>> extends Model<M> implements IBean {


	/**
	 *获取id
	 */
	public Long getId() {
		return get("id");
	}

	/**
	 *设置id
	 */
	public void setId(Long id) {
		set("id",id);
	}

	/**
	 *获取订单编号
	 */
	public String getCode() {
		return get("code");
	}

	/**
	 *设置订单编号
	 */
	public void setCode(String code) {
		set("code",code);
	}

	/**
	 *获取订单类型,0：微信线上订单、1：线下订单
	 */
	public String getType() {
		return get("type");
	}

	/**
	 *设置订单类型,0：微信线上订单、1：线下订单
	 */
	public void setType(String type) {
		set("type",type);
	}

	/**
	 *获取下单人
	 */
	public Long getMemberId() {
		return get("memberId");
	}

	/**
	 *设置下单人
	 */
	public void setMemberId(Long memberId) {
		set("memberId",memberId);
	}

	/**
	 *获取金额修改人
	 */
	public String getModifyUser() {
		return get("modifyUser");
	}

	/**
	 *设置金额修改人
	 */
	public void setModifyUser(String modifyUser) {
		set("modifyUser",modifyUser);
	}

	/**
	 *获取是否手动修改金额,0：否，1：是
	 */
	public String getPriceModified() {
		return get("priceModified");
	}

	/**
	 *设置是否手动修改金额,0：否，1：是
	 */
	public void setPriceModified(String priceModified) {
		set("priceModified",priceModified);
	}

	/**
	 *获取优惠前金额
	 */
	public Double getOldPrice() {
		return get("oldPrice");
	}

	/**
	 *设置优惠前金额
	 */
	public void setOldPrice(Double oldPrice) {
		set("oldPrice",oldPrice);
	}

	/**
	 *获取享受折扣
	 */
	public Double getDiscount() {
		return get("discount");
	}

	/**
	 *设置享受折扣
	 */
	public void setDiscount(Double discount) {
		set("discount",discount);
	}

	/**
	 *获取积分抵换金额
	 */
	public Double getIntegralPrice() {
		return get("integralPrice");
	}

	/**
	 *设置积分抵换金额
	 */
	public void setIntegralPrice(Double integralPrice) {
		set("integralPrice",integralPrice);
	}

	/**
	 *获取订单实付金额
	 */
	public Double getTotalPrice() {
		return get("totalPrice");
	}

	/**
	 *设置订单实付金额
	 */
	public void setTotalPrice(Double totalPrice) {
		set("totalPrice",totalPrice);
	}

	/**
	 *获取是否支付,0:未支付，1：已支付
	 */
	public String getIsPay() {
		return get("isPay");
	}

	/**
	 *设置是否支付,0:未支付，1：已支付
	 */
	public void setIsPay(String isPay) {
		set("isPay",isPay);
	}

	/**
	 *获取是否发货,0：未发货，1：已发货
	 */
	public String getIsSend() {
		return get("isSend");
	}

	/**
	 *设置是否发货,0：未发货，1：已发货
	 */
	public void setIsSend(String isSend) {
		set("isSend",isSend);
	}

	/**
	 *获取是否收货，0：未收货，1：已收货
	 */
	public String getIsReceive() {
		return get("isReceive");
	}

	/**
	 *设置是否收货，0：未收货，1：已收货
	 */
	public void setIsReceive(String isReceive) {
		set("isReceive",isReceive);
	}

	/**
	 *获取订单备注
	 */
	public String getRemark() {
		return get("remark");
	}

	/**
	 *设置订单备注
	 */
	public void setRemark(String remark) {
		set("remark",remark);
	}

	/**
	 *获取配送方式,0:商家配送，1：到点自提
	 */
	public String getDelWay() {
		return get("delWay");
	}

	/**
	 *设置配送方式,0:商家配送，1：到点自提
	 */
	public void setDelWay(String delWay) {
		set("delWay",delWay);
	}

	/**
	 *获取提货时间
	 */
	public Date getGetTime() {
		return get("getTime");
	}

	/**
	 *设置提货时间
	 */
	public void setGetTime(Date getTime) {
		set("getTime",getTime);
	}

	/**
	 *获取收货人姓名
	 */
	public String getReveiveName() {
		return get("reveiveName");
	}

	/**
	 *设置收货人姓名
	 */
	public void setReveiveName(String reveiveName) {
		set("reveiveName",reveiveName);
	}

	/**
	 *获取收货人电话
	 */
	public String getPhone() {
		return get("phone");
	}

	/**
	 *设置收货人电话
	 */
	public void setPhone(String phone) {
		set("phone",phone);
	}

	/**
	 *获取收货人地址
	 */
	public String getAddress() {
		return get("address");
	}

	/**
	 *设置收货人地址
	 */
	public void setAddress(String address) {
		set("address",address);
	}

	/**
	 *获取下单时间
	 */
	public Date getOrderTime() {
		return get("orderTime");
	}

	/**
	 *设置下单时间
	 */
	public void setOrderTime(Date orderTime) {
		set("orderTime",orderTime);
	}

	/**
	 *获取支付方式,0：微信支付、1：现金支付、2：支付宝、3：银行卡
	 */
	public String getPayway() {
		return get("payway");
	}

	/**
	 *设置支付方式,0：微信支付、1：现金支付、2：支付宝、3：银行卡
	 */
	public void setPayway(String payway) {
		set("payway",payway);
	}

	/**
	 *获取支付时间
	 */
	public Date getPayTime() {
		return get("payTime");
	}

	/**
	 *设置支付时间
	 */
	public void setPayTime(Date payTime) {
		set("payTime",payTime);
	}

	/**
	 *获取发货时间
	 */
	public Date getSendTime() {
		return get("sendTime");
	}

	/**
	 *设置发货时间
	 */
	public void setSendTime(Date sendTime) {
		set("sendTime",sendTime);
	}

	/**
	 *获取收货时间
	 */
	public Date getReceiveTime() {
		return get("receiveTime");
	}

	/**
	 *设置收货时间
	 */
	public void setReceiveTime(Date receiveTime) {
		set("receiveTime",receiveTime);
	}

	/**
	 *获取0：正常,1：作废
	 */
	public String getStatus() {
		return get("status");
	}

	/**
	 *设置0：正常,1：作废
	 */
	public void setStatus(String status) {
		set("status",status);
	}

	/**
	 *获取获得积分
	 */
	public Integer getIntegral() {
		return get("integral");
	}

	/**
	 *设置获得积分
	 */
	public void setIntegral(Integer integral) {
		set("integral",integral);
	}

	/**
	 *获取余额支付
	 */
	public Double getBalancePay() {
		return get("balancePay");
	}

	/**
	 *设置余额支付
	 */
	public void setBalancePay(Double balancePay) {
		set("balancePay",balancePay);
	}

	/**
	 *获取用户使用优惠券编号列表，逗号隔开
	 */
	public String getUserCoupons() {
		return get("userCoupons");
	}

	/**
	 *设置用户使用优惠券编号列表，逗号隔开
	 */
	public void setUserCoupons(String userCoupons) {
		set("userCoupons",userCoupons);
	}

	/**
	 *获取优惠券支付
	 */
	public Integer getCouponsPay() {
		return get("couponsPay");
	}

	/**
	 *设置优惠券支付
	 */
	public void setCouponsPay(Integer couponsPay) {
		set("couponsPay",couponsPay);
	}

	/**
	 *获取满减金额
	 */
	public Integer getSubtractMoney() {
		return get("subtractMoney");
	}

	/**
	 *设置满减金额
	 */
	public void setSubtractMoney(Integer subtractMoney) {
		set("subtractMoney",subtractMoney);
	}

}
