package com.block.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import java.util.*;

/**
 * Generated by JFinal.
*/
@SuppressWarnings("serial")
public class BaseShoppingCar <M extends BaseShoppingCar<M>> extends Model<M> implements IBean {


	/**
	 *获取id
	 */
	public Long getId() {
		return get("id");
	}

	/**
	 *设置id
	 */
	public void setId(Long id) {
		set("id",id);
	}

	/**
	 *获取会员id
	 */
	public Long getMemberid() {
		return get("memberid");
	}

	/**
	 *设置会员id
	 */
	public void setMemberid(Long memberid) {
		set("memberid",memberid);
	}

	/**
	 *获取商品详情id
	 */
	public Long getGoodsDetailId() {
		return get("goodsDetailId");
	}

	/**
	 *设置商品详情id
	 */
	public void setGoodsDetailId(Long goodsDetailId) {
		set("goodsDetailId",goodsDetailId);
	}

	/**
	 *获取数量
	 */
	public Integer getNum() {
		return get("num");
	}

	/**
	 *设置数量
	 */
	public void setNum(Integer num) {
		set("num",num);
	}

	/**
	 *获取添加时间
	 */
	public Date getAddTime() {
		return get("addTime");
	}

	/**
	 *设置添加时间
	 */
	public void setAddTime(Date addTime) {
		set("addTime",addTime);
	}

}
