package com.block.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import java.util.*;

/**
 * Generated by JFinal.
*/
@SuppressWarnings("serial")
public class BaseOrderDetail <M extends BaseOrderDetail<M>> extends Model<M> implements IBean {


	/**
	 *获取id
	 */
	public Long getId() {
		return get("id");
	}

	/**
	 *设置id
	 */
	public void setId(Long id) {
		set("id",id);
	}

	/**
	 *获取订单id
	 */
	public Long getOrderId() {
		return get("orderId");
	}

	/**
	 *设置订单id
	 */
	public void setOrderId(Long orderId) {
		set("orderId",orderId);
	}

	/**
	 *获取子商品id
	 */
	public Long getGoodsDetailId() {
		return get("goodsDetailId");
	}

	/**
	 *设置子商品id
	 */
	public void setGoodsDetailId(Long goodsDetailId) {
		set("goodsDetailId",goodsDetailId);
	}

	/**
	 *获取商品名称
	 */
	public String getGoodsName() {
		return get("goodsName");
	}

	/**
	 *设置商品名称
	 */
	public void setGoodsName(String goodsName) {
		set("goodsName",goodsName);
	}

	/**
	 *获取尺寸
	 */
	public Long getSizeId() {
		return get("sizeId");
	}

	/**
	 *设置尺寸
	 */
	public void setSizeId(Long sizeId) {
		set("sizeId",sizeId);
	}

	/**
	 *获取颜色
	 */
	public Long getColorId() {
		return get("colorId");
	}

	/**
	 *设置颜色
	 */
	public void setColorId(Long colorId) {
		set("colorId",colorId);
	}

	/**
	 *获取成本价
	 */
	public Double getCostPrice() {
		return get("costPrice");
	}

	/**
	 *设置成本价
	 */
	public void setCostPrice(Double costPrice) {
		set("costPrice",costPrice);
	}

	/**
	 *获取吊牌价
	 */
	public Double getOldPrice() {
		return get("oldPrice");
	}

	/**
	 *设置吊牌价
	 */
	public void setOldPrice(Double oldPrice) {
		set("oldPrice",oldPrice);
	}

	/**
	 *获取成交价
	 */
	public Double getPrice() {
		return get("price");
	}

	/**
	 *设置成交价
	 */
	public void setPrice(Double price) {
		set("price",price);
	}

	/**
	 *获取折扣价
	 */
	public Double getVipPrice() {
		return get("vipPrice");
	}

	/**
	 *设置折扣价
	 */
	public void setVipPrice(Double vipPrice) {
		set("vipPrice",vipPrice);
	}

	/**
	 *获取购买数量
	 */
	public Integer getAmount() {
		return get("amount");
	}

	/**
	 *设置购买数量
	 */
	public void setAmount(Integer amount) {
		set("amount",amount);
	}

	/**
	 *获取合计
	 */
	public Double getTotalPrice() {
		return get("totalPrice");
	}

	/**
	 *设置合计
	 */
	public void setTotalPrice(Double totalPrice) {
		set("totalPrice",totalPrice);
	}

	/**
	 *获取折扣
	 */
	public Double getDiscount() {
		return get("discount");
	}

	/**
	 *设置折扣
	 */
	public void setDiscount(Double discount) {
		set("discount",discount);
	}

	/**
	 *获取成交均价
	 */
	public Double getAvgprice() {
		return get("avgprice");
	}

	/**
	 *设置成交均价
	 */
	public void setAvgprice(Double avgprice) {
		set("avgprice",avgprice);
	}

}
