package com.block.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import java.util.*;

/**
 * Generated by JFinal.
*/
@SuppressWarnings("serial")
public class BaseLoginHistory <M extends BaseLoginHistory<M>> extends Model<M> implements IBean {


	/**
	 *获取id
	 */
	public Long getId() {
		return get("id");
	}

	/**
	 *设置id
	 */
	public void setId(Long id) {
		set("id",id);
	}

	/**
	 *获取会员id
	 */
	public Long getMemberId() {
		return get("memberId");
	}

	/**
	 *设置会员id
	 */
	public void setMemberId(Long memberId) {
		set("memberId",memberId);
	}

	/**
	 *获取登录时间
	 */
	public Date getLoginTime() {
		return get("loginTime");
	}

	/**
	 *设置登录时间
	 */
	public void setLoginTime(Date loginTime) {
		set("loginTime",loginTime);
	}

	/**
	 *获取登录ip
	 */
	public String getIpAddr() {
		return get("ipAddr");
	}

	/**
	 *设置登录ip
	 */
	public void setIpAddr(String ipAddr) {
		set("ipAddr",ipAddr);
	}

}
