package com.block.common.model.base;

import java.util.Date;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRegion<M extends BaseRegion<M>> extends Model<M> implements IBean {


	public Integer getADDSID() {
		return get("ADDSID");
	}

	public void setADDSID(Integer aDDSID) {
		set("ADDSID", aDDSID);
	}

	public Integer getCode() {
		return get("code");
	}

	public void setCode(Integer code) {
		set("code", code);
	}

	public Integer getSuperiorCode() {
		return get("SuperiorCode");
	}

	public void setSuperiorCode(Integer SuperiorCode) {
		set("SuperiorCode", SuperiorCode);
	}

	public String getName() {
		return get("name");
	}

	public void setName(String name) {
		set("name", name);
	}

	public Integer getType() {
		return get("type");
	}

	public void setType(Integer type) {
		set("type", type);
	}

	public Integer getLevel() {
		return get("level");
	}

	public void setLevel(Integer level) {
		set("level", level);
	}

	public Integer getIsProvince() {
		return get("isProvince");
	}

	public void setIsProvince(Integer isProvince) {
		set("isProvince", isProvince);
	}

	public Integer getCityClassify() {
		return get("CityClassify");
	}

	public void setCityClassify(Integer CityClassify) {
		set("CityClassify", CityClassify);
	}

	public String getAbb() {
		return get("Abb");
	}

	public void setAbb(String Abb) {
		set("Abb", Abb);
	}

	public String getSSP() {
		return get("SSP");
	}

	public void setSSP(String SSP) {
		set("SSP", SSP);
	}

	public String getPinyin() {
		return get("pinyin");
	}

	public void setPinyin(String pinyin) {
		set("pinyin", pinyin);
	}

	public Integer getProvinceCode() {
		return get("ProvinceCode");
	}

	public void setProvinceCode(Integer ProvinceCode) {
		set("ProvinceCode", ProvinceCode);
	}

	public String getProvinceName() {
		return get("ProvinceName");
	}

	public void setProvinceName(String ProvinceName) {
		set("ProvinceName", ProvinceName);
	}

	public String getProvincePinYin() {
		return get("ProvincePinYin");
	}

	public void setProvincePinYin(String ProvincePinYin) {
		set("ProvincePinYin", ProvincePinYin);
	}

	public Integer getCityCode() {
		return get("CityCode");
	}

	public void setCityCode(Integer CityCode) {
		set("CityCode", CityCode);
	}

	public String getCityName() {
		return get("CityName");
	}

	public void setCityName(String CityName) {
		set("CityName", CityName);
	}

	public String getCityPinYin() {
		return get("CityPinYin");
	}

	public void setCityPinYin(String CityPinYin) {
		set("CityPinYin", CityPinYin);
	}

	public Integer getAreaCode() {
		return get("AreaCode");
	}

	public void setAreaCode(Integer AreaCode) {
		set("AreaCode", AreaCode);
	}

	public String getAreaName() {
		return get("AreaName");
	}

	public void setAreaName(String AreaName) {
		set("AreaName", AreaName);
	}

	public String getAreaPinYin() {
		return get("AreaPinYin");
	}

	public void setAreaPinYin(String AreaPinYin) {
		set("AreaPinYin", AreaPinYin);
	}

	public Integer getStatus() {
		return get("Status");
	}

	public void setStatus(Integer Status) {
		set("Status", Status);
	}

	public Integer getCreateStaff() {
		return get("CreateStaff");
	}

	public void setCreateStaff(Integer CreateStaff) {
		set("CreateStaff", CreateStaff);
	}

	public Date getCreateTime() {
		return get("CreateTime");
	}

	public void setCreateTime(Date CreateTime) {
		set("CreateTime", CreateTime);
	}

	public Integer getUpdateStaff() {
		return get("UpdateStaff");
	}

	public void setUpdateStaff(Integer updateStaff) {
		set("UpdateStaff", updateStaff);
	}

	public Date getUpdateTime() {
		return get("UpdateTime");
	}

	public void setUpdateTime(Date updateTime) {
		set("UpdateTime", updateTime);
	}

	public Integer getIsDelete() {
		return get("IsDelete");
	}

	public void setIsDelete(Integer isDelete) {
		set("IsDelete", isDelete);
	}

	public String getDES() {
		return get("DES");
	}

	public void setDES(String dES) {
		set("DES", dES);
	}

}
