package com.block.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import java.util.*;

/**
 * Generated by JFinal.
*/
@SuppressWarnings("serial")
public class BaseContent <M extends BaseContent<M>> extends Model<M> implements IBean {


	/**
	 *获取id
	 */
	public Long getId() {
		return get("id");
	}

	/**
	 *设置id
	 */
	public void setId(Long id) {
		set("id",id);
	}

	/**
	 *获取所属栏目id
	 */
	public Long getProgramId() {
		return get("programId");
	}

	/**
	 *设置所属栏目id
	 */
	public void setProgramId(Long programId) {
		set("programId",programId);
	}

	/**
	 *获取标题
	 */
	public String getTitle() {
		return get("title");
	}

	/**
	 *设置标题
	 */
	public void setTitle(String title) {
		set("title",title);
	}

	/**
	 *获取副标题
	 */
	public String getSubtitle() {
		return get("subtitle");
	}

	/**
	 *设置副标题
	 */
	public void setSubtitle(String subtitle) {
		set("subtitle",subtitle);
	}

	/**
	 *获取内容
	 */
	public String getContent() {
		return get("content");
	}

	/**
	 *设置内容
	 */
	public void setContent(String content) {
		set("content",content);
	}

	/**
	 *获取内容图片,关联附件表
	 */
	public String getImg() {
		return get("img");
	}

	/**
	 *设置内容图片,关联附件表
	 */
	public void setImg(String img) {
		set("img",img);
	}

	/**
	 *获取生效时间起
	 */
	public Date getStartTime() {
		return get("startTime");
	}

	/**
	 *设置生效时间起
	 */
	public void setStartTime(Date startTime) {
		set("startTime",startTime);
	}

	/**
	 *获取生效时间止
	 */
	public Date getEndTime() {
		return get("endTime");
	}

	/**
	 *设置生效时间止
	 */
	public void setEndTime(Date endTime) {
		set("endTime",endTime);
	}

	/**
	 *获取点击量
	 */
	public Long getHits() {
		return get("hits");
	}

	/**
	 *设置点击量
	 */
	public void setHits(Long hits) {
		set("hits",hits);
	}

	/**
	 *获取排序
	 */
	public Long getSortno() {
		return get("sortno");
	}

	/**
	 *设置排序
	 */
	public void setSortno(Long sortno) {
		set("sortno",sortno);
	}

	/**
	 *获取备注
	 */
	public String getComments() {
		return get("comments");
	}

	/**
	 *设置备注
	 */
	public void setComments(String comments) {
		set("comments",comments);
	}

	/**
	 *获取创建时间
	 */
	public Date getCreateTime() {
		return get("createTime");
	}

	/**
	 *设置创建时间
	 */
	public void setCreateTime(Date createTime) {
		set("createTime",createTime);
	}

	/**
	 *获取最后一次更新时间
	 */
	public Date getUpdateTime() {
		return get("updateTime");
	}

	/**
	 *设置最后一次更新时间
	 */
	public void setUpdateTime(Date updateTime) {
		set("updateTime",updateTime);
	}

	/**
	 *获取url
	 */
	public String getUrl() {
		return get("url");
	}

	/**
	 *设置url
	 */
	public void setUrl(String url) {
		set("url",url);
	}

}
