package com.block.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import java.util.*;

/**
 * Generated by JFinal.
*/
@SuppressWarnings("serial")
public class BaseGoodsBrowseHis <M extends BaseGoodsBrowseHis<M>> extends Model<M> implements IBean {


	/**
	 *获取id
	 */
	public Long getId() {
		return get("id");
	}

	/**
	 *设置id
	 */
	public void setId(Long id) {
		set("id",id);
	}

	/**
	 *获取会员Id
	 */
	public Long getMemberId() {
		return get("memberId");
	}

	/**
	 *设置会员Id
	 */
	public void setMemberId(Long memberId) {
		set("memberId",memberId);
	}

	/**
	 *获取商品id
	 */
	public Long getGoodsId() {
		return get("goodsId");
	}

	/**
	 *设置商品id
	 */
	public void setGoodsId(Long goodsId) {
		set("goodsId",goodsId);
	}

	/**
	 *获取ip地址
	 */
	public String getIpAddr() {
		return get("ipAddr");
	}

	/**
	 *设置ip地址
	 */
	public void setIpAddr(String ipAddr) {
		set("ipAddr",ipAddr);
	}

	/**
	 *获取浏览时间
	 */
	public Date getBrowseTime() {
		return get("browseTime");
	}

	/**
	 *设置浏览时间
	 */
	public void setBrowseTime(Date browseTime) {
		set("browseTime",browseTime);
	}

}
