package com.block.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import java.util.*;

/**
 * Generated by JFinal.
*/
@SuppressWarnings("serial")
public class BaseBrand <M extends BaseBrand<M>> extends Model<M> implements IBean {


	/**
	 *获取id
	 */
	public Long getId() {
		return get("id");
	}

	/**
	 *设置id
	 */
	public void setId(Long id) {
		set("id",id);
	}

	/**
	 *获取类型：0:设计师品牌，1：联名合作
	 */
	public String getType() {
		return get("type");
	}

	/**
	 *设置类型：0:设计师品牌，1：联名合作
	 */
	public void setType(String type) {
		set("type",type);
	}

	/**
	 *获取名称
	 */
	public String getName() {
		return get("name");
	}

	/**
	 *设置名称
	 */
	public void setName(String name) {
		set("name",name);
	}

	/**
	 *获取品牌介绍
	 */
	public String getIntro() {
		return get("intro");
	}

	/**
	 *设置品牌介绍
	 */
	public void setIntro(String intro) {
		set("intro",intro);
	}

	/**
	 *获取默认图片
	 */
	public String getImg() {
		return get("img");
	}

	/**
	 *设置默认图片
	 */
	public void setImg(String img) {
		set("img",img);
	}

	/**
	 *获取状态,0：正常，1：禁用
	 */
	public String getStatus() {
		return get("status");
	}

	/**
	 *设置状态,0：正常，1：禁用
	 */
	public void setStatus(String status) {
		set("status",status);
	}

	/**
	 *获取是否推荐,0:否，1：是
	 */
	public String getIsRecomment() {
		return get("isRecomment");
	}

	/**
	 *设置是否推荐,0:否，1：是
	 */
	public void setIsRecomment(String isRecomment) {
		set("isRecomment",isRecomment);
	}

	/**
	 *获取排序
	 */
	public Integer getSortno() {
		return get("sortno");
	}

	/**
	 *设置排序
	 */
	public void setSortno(Integer sortno) {
		set("sortno",sortno);
	}

	/**
	 *获取创建时间
	 */
	public Date getCreateTime() {
		return get("createTime");
	}

	/**
	 *设置创建时间
	 */
	public void setCreateTime(Date createTime) {
		set("createTime",createTime);
	}

	/**
	 *获取更新时间
	 */
	public Date getUpdateTime() {
		return get("updateTime");
	}

	/**
	 *设置更新时间
	 */
	public void setUpdateTime(Date updateTime) {
		set("updateTime",updateTime);
	}

	/**
	 *获取detailIntro
	 */
	public String getDetailIntro() {
		return get("detailIntro");
	}

	/**
	 *设置detailIntro
	 */
	public void setDetailIntro(String detailIntro) {
		set("detailIntro",detailIntro);
	}

}
