package com.block.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal.
*/
@SuppressWarnings("serial")
public class BaseCooperateGoods <M extends BaseCooperateGoods<M>> extends Model<M> implements IBean {


	/**
	 *获取id
	 */
	public Long getId() {
		return get("id");
	}

	/**
	 *设置id
	 */
	public void setId(Long id) {
		set("id",id);
	}

	/**
	 *获取cooperateId
	 */
	public Long getCooperateId() {
		return get("cooperateId");
	}

	/**
	 *设置cooperateId
	 */
	public void setCooperateId(Long cooperateId) {
		set("cooperateId",cooperateId);
	}

	/**
	 *获取goodsId
	 */
	public Long getGoodsId() {
		return get("goodsId");
	}

	/**
	 *设置goodsId
	 */
	public void setGoodsId(Long goodsId) {
		set("goodsId",goodsId);
	}

}
