package com.block.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import java.util.*;

/**
 * Generated by JFinal.
*/
@SuppressWarnings("serial")
public class BasePointLog <M extends BasePointLog<M>> extends Model<M> implements IBean {


	/**
	 *获取id
	 */
	public Long getId() {
		return get("id");
	}

	/**
	 *设置id
	 */
	public void setId(Long id) {
		set("id",id);
	}

	/**
	 *获取 会员id
	 */
	public Long getMemberId() {
		return get("memberId");
	}

	/**
	 *设置 会员id
	 */
	public void setMemberId(Long memberId) {
		set("memberId",memberId);
	}

	/**
	 *获取类型,0:增加，1：减少
	 */
	public String getType() {
		return get("type");
	}

	/**
	 *设置类型,0:增加，1：减少
	 */
	public void setType(String type) {
		set("type",type);
	}

	/**
	 *获取增加、减少原因，0：消费，1：注册,2:管理员添加,3:推广积分
	 */
	public String getReason() {
		return get("reason");
	}

	/**
	 *设置增加、减少原因，0：消费，1：注册,2:管理员添加,3:推广积分
	 */
	public void setReason(String reason) {
		set("reason",reason);
	}

	/**
	 *获取增加、减少积分数量
	 */
	public Integer getPoint() {
		return get("point");
	}

	/**
	 *设置增加、减少积分数量
	 */
	public void setPoint(Integer point) {
		set("point",point);
	}

	/**
	 *获取订单号，如果没有则为空
	 */
	public Long getOrderId() {
		return get("orderId");
	}

	/**
	 *设置订单号，如果没有则为空
	 */
	public void setOrderId(Long orderId) {
		set("orderId",orderId);
	}

	/**
	 *获取变更时间
	 */
	public Date getChangeTime() {
		return get("changeTime");
	}

	/**
	 *设置变更时间
	 */
	public void setChangeTime(Date changeTime) {
		set("changeTime",changeTime);
	}

}
