package com.block.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import java.util.*;

/**
 * Generated by JFinal.
*/
@SuppressWarnings("serial")
public class BaseSysSetting <M extends BaseSysSetting<M>> extends Model<M> implements IBean {


	/**
	 *获取id
	 */
	public Long getId() {
		return get("id");
	}

	/**
	 *设置id
	 */
	public void setId(Long id) {
		set("id",id);
	}

	/**
	 *获取key
	 */
	public String getTypekey() {
		return get("typekey");
	}

	/**
	 *设置key
	 */
	public void setTypekey(String typekey) {
		set("typekey",typekey);
	}

	/**
	 *获取value
	 */
	public String getTypevalue() {
		return get("typevalue");
	}

	/**
	 *设置value
	 */
	public void setTypevalue(String typevalue) {
		set("typevalue",typevalue);
	}

	/**
	 *获取remark
	 */
	public String getRemark() {
		return get("remark");
	}

	/**
	 *设置remark
	 */
	public void setRemark(String remark) {
		set("remark",remark);
	}

}
