package com.block.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import java.util.*;

/**
 * Generated by JFinal.
*/
@SuppressWarnings("serial")
public class BaseGoodsDetail <M extends BaseGoodsDetail<M>> extends Model<M> implements IBean {


	/**
	 *获取id
	 */
	public Long getId() {
		return get("id");
	}

	/**
	 *设置id
	 */
	public void setId(Long id) {
		set("id",id);
	}

	/**
	 *获取商品id
	 */
	public Long getGoodsId() {
		return get("goodsId");
	}

	/**
	 *设置商品id
	 */
	public void setGoodsId(Long goodsId) {
		set("goodsId",goodsId);
	}

	/**
	 *获取编号
	 */
	public String getDetailcode() {
		return get("detailcode");
	}

	/**
	 *设置编号
	 */
	public void setDetailcode(String detailcode) {
		set("detailcode",detailcode);
	}

	/**
	 *获取尺寸
	 */
	public Long getSizeId() {
		return get("sizeId");
	}

	/**
	 *设置尺寸
	 */
	public void setSizeId(Long sizeId) {
		set("sizeId",sizeId);
	}

	/**
	 *获取颜色
	 */
	public Long getColorId() {
		return get("colorId");
	}

	/**
	 *设置颜色
	 */
	public void setColorId(Long colorId) {
		set("colorId",colorId);
	}

	/**
	 *获取规格三
	 */
	public Long getSpecId3() {
		return get("specId3");
	}

	/**
	 *设置规格三
	 */
	public void setSpecId3(Long specId3) {
		set("specId3",specId3);
	}

	/**
	 *获取规格四
	 */
	public Long getSpecId4() {
		return get("specId4");
	}

	/**
	 *设置规格四
	 */
	public void setSpecId4(Long specId4) {
		set("specId4",specId4);
	}

	/**
	 *获取成本价
	 */
	public Double getCostPrice() {
		return get("costPrice");
	}

	/**
	 *设置成本价
	 */
	public void setCostPrice(Double costPrice) {
		set("costPrice",costPrice);
	}

	/**
	 *获取吊牌价
	 */
	public Double getOldPrice() {
		return get("oldPrice");
	}

	/**
	 *设置吊牌价
	 */
	public void setOldPrice(Double oldPrice) {
		set("oldPrice",oldPrice);
	}

	/**
	 *获取成交价
	 */
	public Double getPrice() {
		return get("price");
	}

	/**
	 *设置成交价
	 */
	public void setPrice(Double price) {
		set("price",price);
	}

	/**
	 *获取折扣价
	 */
	public Double getVipPrice() {
		return get("vipPrice");
	}

	/**
	 *设置折扣价
	 */
	public void setVipPrice(Double vipPrice) {
		set("vipPrice",vipPrice);
	}

	/**
	 *获取库存数量
	 */
	public Integer getAmount() {
		return get("amount");
	}

	/**
	 *设置库存数量
	 */
	public void setAmount(Integer amount) {
		set("amount",amount);
	}

	/**
	 *获取状态,0:未上架、1：上架、2：下架
	 */
	public String getStatus() {
		return get("status");
	}

	/**
	 *设置状态,0:未上架、1：上架、2：下架
	 */
	public void setStatus(String status) {
		set("status",status);
	}

	/**
	 *获取更新时间
	 */
	public Date getUpdateTime() {
		return get("updateTime");
	}

	/**
	 *设置更新时间
	 */
	public void setUpdateTime(Date updateTime) {
		set("updateTime",updateTime);
	}

	/**
	 *获取排序
	 */
	public Long getSortno() {
		return get("sortno");
	}

	/**
	 *设置排序
	 */
	public void setSortno(Long sortno) {
		set("sortno",sortno);
	}

}
