package com.block.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import java.util.*;

/**
 * Generated by JFinal.
*/
@SuppressWarnings("serial")
public class BaseImgs <M extends BaseImgs<M>> extends Model<M> implements IBean {


	/**
	 *获取id
	 */
	public Long getId() {
		return get("id");
	}

	/**
	 *设置id
	 */
	public void setId(Long id) {
		set("id",id);
	}

	/**
	 *获取类型，0：品牌，1：商品
	 */
	public String getType() {
		return get("type");
	}

	/**
	 *设置类型，0：品牌，1：商品
	 */
	public void setType(String type) {
		set("type",type);
	}

	/**
	 *获取业务单据ID
	 */
	public Long getReceiptID() {
		return get("receiptID");
	}

	/**
	 *设置业务单据ID
	 */
	public void setReceiptID(Long receiptID) {
		set("receiptID",receiptID);
	}

	/**
	 *获取路径
	 */
	public String getPath() {
		return get("path");
	}

	/**
	 *设置路径
	 */
	public void setPath(String path) {
		set("path",path);
	}

}
