package com.block.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMsg<M extends BaseMsg<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setMsgtype(java.lang.String msgtype) {
		set("msgtype", msgtype);
	}

	public java.lang.String getMsgtype() {
		return get("msgtype");
	}

	public void setPicaddr(java.lang.String picaddr) {
		set("picaddr", picaddr);
	}

	public java.lang.String getPicaddr() {
		return get("picaddr");
	}

	public void setPic(java.lang.String pic) {
		set("pic", pic);
	}

	public java.lang.String getPic() {
		return get("pic");
	}

	public void setContenttype(java.lang.String contenttype) {
		set("contenttype", contenttype);
	}

	public java.lang.String getContenttype() {
		return get("contenttype");
	}

	public void setLinkaddr(java.lang.String linkaddr) {
		set("linkaddr", linkaddr);
	}

	public java.lang.String getLinkaddr() {
		return get("linkaddr");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setFdorder(java.lang.String fdorder) {
		set("fdorder", fdorder);
	}

	public java.lang.String getFdorder() {
		return get("fdorder");
	}

}
