package com.block.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import java.util.*;

/**
 * Generated by JFinal.
*/
@SuppressWarnings("serial")
public class BaseMemberAddress <M extends BaseMemberAddress<M>> extends Model<M> implements IBean {


	/**
	 *获取id
	 */
	public Long getId() {
		return get("id");
	}

	/**
	 *设置id
	 */
	public void setId(Long id) {
		set("id",id);
	}

	/**
	 *获取会员id 
	 */
	public Long getMemberId() {
		return get("memberId");
	}

	/**
	 *设置会员id 
	 */
	public void setMemberId(Long memberId) {
		set("memberId",memberId);
	}

	/**
	 *获取收货人姓名
	 */
	public String getName() {
		return get("name");
	}

	/**
	 *设置收货人姓名
	 */
	public void setName(String name) {
		set("name",name);
	}

	/**
	 *获取地址id
	 */
	public Integer getAddressId() {
		return get("addressId");
	}

	/**
	 *设置地址id
	 */
	public void setAddressId(Integer addressId) {
		set("addressId",addressId);
	}

	/**
	 *获取详细地址
	 */
	public String getDetailAddress() {
		return get("detailAddress");
	}

	/**
	 *设置详细地址
	 */
	public void setDetailAddress(String detailAddress) {
		set("detailAddress",detailAddress);
	}

	/**
	 *获取收货人地址
	 */
	public String getAddress() {
		return get("address");
	}

	/**
	 *设置收货人地址
	 */
	public void setAddress(String address) {
		set("address",address);
	}

	/**
	 *获取联系电话
	 */
	public String getPhone() {
		return get("phone");
	}

	/**
	 *设置联系电话
	 */
	public void setPhone(String phone) {
		set("phone",phone);
	}

	/**
	 *获取是否默认,0:否，1：是
	 */
	public String getIsDefault() {
		return get("isDefault");
	}

	/**
	 *设置是否默认,0:否，1：是
	 */
	public void setIsDefault(String isDefault) {
		set("isDefault",isDefault);
	}

	/**
	 *获取添加时间
	 */
	public Date getCreateTime() {
		return get("createTime");
	}

	/**
	 *设置添加时间
	 */
	public void setCreateTime(Date createTime) {
		set("createTime",createTime);
	}

}
