package com.block.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("t_msg", "id", Msg.class);
		arp.addMapping("t_region", "ADDSID", Region.class);
		arp.addMapping("t_member", "id", Member.class);
		arp.addMapping("t_brand", "id", Brand.class);
		arp.addMapping("t_goods", "id", Goods.class);
		arp.addMapping("t_goods_detail", "id", GoodsDetail.class);
		arp.addMapping("t_imgs", "id", Imgs.class);
		arp.addMapping("t_level_setting", "id", LevelSetting.class);
		arp.addMapping("t_order", "id", Order.class);
		arp.addMapping("t_order_detail", "id", OrderDetail.class);
		arp.addMapping("t_point_log", "id", PointLog.class);
		arp.addMapping("t_collect", "id", Collect.class);
		arp.addMapping("t_shopping_car", "id", ShoppingCar.class);
		arp.addMapping("t_content", "id", Content.class);
		arp.addMapping("t_cooperate", "id", Cooperate.class);
		arp.addMapping("t_cooperate_goods", "id", CooperateGoods.class);
		arp.addMapping("t_recharge_rule", "id", RechargeRule.class);
		arp.addMapping("t_full_rule", "id", FullRule.class);
		arp.addMapping("t_login_history", "id", LoginHistory.class);
		arp.addMapping("t_goods_browseHis", "id", GoodsBrowseHis.class);
		arp.addMapping("t_sys_setting", "id", SysSetting.class);
		arp.addMapping("t_coupon", "id", Coupon.class);
		arp.addMapping("t_member_coupon", "id", MemberCoupon.class);
		arp.addMapping("t_member_typechange", "id", MemberTypeChange.class);
		arp.addMapping("t_member_address", "id", MemberAddress.class);
		arp.addMapping("t_balance_record", "id", BalanceRecord.class);
		arp.addMapping("t_type", "id", Type.class);
		arp.addMapping("t_member_label", "id", MemberLabel.class);
	}
}

