package com.block.common.model;

import com.block.common.model.base.BaseBalanceRecord;
/**
 * Generated by JFinal.
*/
@SuppressWarnings("serial")
public class BalanceRecord extends BaseBalanceRecord<BalanceRecord>{

	public static final BalanceRecord dao = new BalanceRecord();

}
