package com.block.common.model;

import com.block.common.model.base.BaseBrand;
/**
 * Generated by JFinal.
*/
@SuppressWarnings("serial")
public class Brand extends BaseBrand<Brand>{

	public static final Brand dao = new Brand();

}
