package com.block.common.model;

import com.block.common.model.base.BaseCollect;
/**
 * Generated by JFinal.
*/
@SuppressWarnings("serial")
public class Collect extends BaseCollect<Collect>{

	public static final Collect dao = new Collect();

}
