package com.block.common.model;

import com.block.common.model.base.BaseContent;
/**
 * Generated by JFinal.
*/
@SuppressWarnings("serial")
public class Content extends BaseContent<Content>{

	public static final Content dao = new Content();

}
