package com.block.common.model;

import com.block.common.model.base.BaseCooperateGoods;
/**
 * Generated by JFinal.
*/
@SuppressWarnings("serial")
public class CooperateGoods extends BaseCooperateGoods<CooperateGoods>{

	public static final CooperateGoods dao = new CooperateGoods();

}
