package com.block.common.model;

import com.block.common.model.base.BaseCooperate;
/**
 * Generated by JFinal.
*/
@SuppressWarnings("serial")
public class Cooperate extends BaseCooperate<Cooperate>{

	public static final Cooperate dao = new Cooperate();

}
