package com.block.common.model;

import com.block.common.model.base.BaseFullRule;
/**
 * Generated by JFinal.
*/
@SuppressWarnings("serial")
public class FullRule extends BaseFullRule<FullRule>{

	public static final FullRule dao = new FullRule();

}
