package com.block.common.model;

import com.block.common.model.base.BaseGoodsDetail;
/**
 * Generated by JFinal.
*/
@SuppressWarnings("serial")
public class GoodsDetail extends BaseGoodsDetail<GoodsDetail>{

	public static final GoodsDetail dao = new GoodsDetail();

}
