package com.block.common.model;

import com.block.common.model.base.BaseGoodsBrowseHis;
/**
 * Generated by JFinal.
*/
@SuppressWarnings("serial")
public class GoodsBrowseHis extends BaseGoodsBrowseHis<GoodsBrowseHis>{

	public static final GoodsBrowseHis dao = new GoodsBrowseHis();

}
