package com.block.common.model;

import com.block.common.model.base.BaseImgs;
/**
 * Generated by JFinal.
*/
@SuppressWarnings("serial")
public class Imgs extends BaseImgs<Imgs>{

	public static final Imgs dao = new Imgs();

}
