package com.block.common.model;

import com.block.common.model.base.BaseLevelSetting;
/**
 * Generated by JFinal.
*/
@SuppressWarnings("serial")
public class LevelSetting extends BaseLevelSetting<LevelSetting>{

	public static final LevelSetting dao = new LevelSetting();
	
	public LevelSetting getCurrentLevelByMoney(double money){
		LevelSetting levelSetting=LevelSetting.dao.findFirst("select * from t_level_setting where levelstart <= ? and levelend >= ?",(int)money,(int)money);
		return levelSetting;
	}

	public LevelSetting getLevelByGrade(int grade){
		LevelSetting levelSetting=LevelSetting.dao.findFirst("select * from t_level_setting where grade= ?",grade);
		return levelSetting;
	}
}
