package com.block.common.model;

import com.block.common.model.base.BaseLoginHistory;
/**
 * Generated by JFinal.
*/
@SuppressWarnings("serial")
public class LoginHistory extends BaseLoginHistory<LoginHistory>{

	public static final LoginHistory dao = new LoginHistory();

}
