package com.block.common.model;

import com.block.common.model.base.BaseMember;
/**
 * Generated by JFinal.
*/
@SuppressWarnings("serial")
public class Member extends BaseMember<Member>{

	public static final Member dao = new Member();

	public Member getMember(String openid) {
		String sql = "select * from t_member where  Openid=?";
		return findFirst(sql,openid);
	}
	
	public Member getMemberById(Long id){
		String sql="select m.*,s.gradename from t_member m"+
				" left join t_level_setting s on m.memberlevel=s.grade where m.id=?";
		return findFirst(sql,id);
	}

}
