package com.block.common.model;

import com.block.common.model.base.BaseMemberLabel;
/**
 * Generated by JFinal.
*/
@SuppressWarnings("serial")
public class MemberLabel extends BaseMemberLabel<MemberLabel>{

	public static final MemberLabel dao = new MemberLabel();

}
