package com.block.common.model;

import com.block.common.model.base.BaseMemberCoupon;
/**
 * Generated by JFinal.
*/
@SuppressWarnings("serial")
public class MemberCoupon extends BaseMemberCoupon<MemberCoupon>{

	public static final MemberCoupon dao = new MemberCoupon();

}
