package com.block.common.model;

import com.block.common.model.base.BaseMemberAddress;
/**
 * Generated by JFinal.
*/
@SuppressWarnings("serial")
public class MemberAddress extends BaseMemberAddress<MemberAddress>{

	public static final MemberAddress dao = new MemberAddress();

}
