package com.block.common.model;

import com.block.common.model.base.BaseMemberTypeChange;
/**
 * Generated by JFinal.
*/
@SuppressWarnings("serial")
public class MemberTypeChange extends BaseMemberTypeChange<MemberTypeChange>{

	public static final MemberTypeChange dao = new MemberTypeChange();

}
