package com.block.common.model;

import com.block.common.model.base.BaseMsg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Msg extends BaseMsg<Msg> {
	public static final Msg dao = new Msg();
}
