package com.block.common.model;

import com.block.common.model.base.BaseOrderDetail;
/**
 * Generated by JFinal.
*/
@SuppressWarnings("serial")
public class OrderDetail extends BaseOrderDetail<OrderDetail>{

	public static final OrderDetail dao = new OrderDetail();

}
