package com.block.common.model;

import com.block.common.model.base.BasePointLog;
/**
 * Generated by JFinal.
*/
@SuppressWarnings("serial")
public class PointLog extends BasePointLog<PointLog>{

	public static final PointLog dao = new PointLog();

}
