package com.block.common.model;

import com.block.common.model.base.BaseRechargeRule;
/**
 * Generated by JFinal.
*/
@SuppressWarnings("serial")
public class RechargeRule extends BaseRechargeRule<RechargeRule>{

	public static final RechargeRule dao = new RechargeRule();

}
