package com.block.common.model;

import com.block.common.model.base.BaseRegion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Region extends BaseRegion<Region> {
	public static final Region dao = new Region();
}
