package com.block.common.model;

import com.block.common.model.base.BaseShoppingCar;
/**
 * Generated by JFinal.
*/
@SuppressWarnings("serial")
public class ShoppingCar extends BaseShoppingCar<ShoppingCar>{

	public static final ShoppingCar dao = new ShoppingCar();

}
