package com.block.common.model;

import com.block.common.model.base.BaseSysSetting;
/**
 * Generated by JFinal.
*/
@SuppressWarnings("serial")
public class SysSetting extends BaseSysSetting<SysSetting>{

	public static final SysSetting dao = new SysSetting();

}
