package com.block.common.model;

import com.block.common.model.base.BaseType;
/**
 * Generated by JFinal.
*/
@SuppressWarnings("serial")
public class Type extends BaseType<Type>{

	public static final Type dao = new Type();

}
